[package]
name = "ws-build"
version = "0.1.0"
edition = "2024"

description = "Build support crate for vercmp-rs workspace"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
bindgen = {version = "0.72.1", optional = true}
cc = "1.2.62"

[features]
# default = ["generate-bindings"]
generate-bindings = ["bindgen"]
