[workspace]
resolver = "2"
members = [
    "alpm-version",
    "apk-version",
    "debian-version",
    "maven-version",
    "rpm-version",
    "semantic-version",
    "vercmp",
    "ws-build",
]
default-members = ["vercmp"]

[profile.dev]
opt-level = 0
debug = 2
lto = false
strip = false
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3           # "z"
lto = "fat"
codegen-units = 8
debug = false
strip = "symbols"
panic = "abort"
incremental = false
overflow-checks = false
