#ifdef __cplusplus
extern "C" {
#endif


#ifndef libvercmp_bindings_h
#define libvercmp_bindings_h

#pragma once

/* Generated with cbindgen:0.29.2 */

/* WARNING: This file is auto-generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Error codes for libvercmp bindings
#define ERROR_NULL_POINTER 100
#define ERROR_INVALID_UTF8 101
#define ERROR_PURL_PARSE   102
#define ERROR_COMPARE      103

// Success comparison codes
#define CMP_EQUAL      0
#define CMP_LESS       -1
#define CMP_GREATER    1


int32_t compare_version_with_purl_type(const char *p,
                                       const char *a,
                                       const char *b);

#endif  /* libvercmp_bindings_h */

#ifdef __cplusplus
}
#endif
