[package]
name = "vercmp-rs"
version = "0.1.2"
edition = "2024"
authors = ["idhyt3r@gmail.com"]
license = "MIT"
description = "Comprehensive version parsing and comparison implementing Package URL (purl) ecosystem rules (SemVer, RPM, APK, DEB, ALPM, etc.)"
readme = "README.md"
homepage = "https://github.com/idhyt/vercmp-rs/tree/main/vercmp"
repository = "https://github.com/idhyt/vercmp-rs"
keywords = ["vercmp", "comparison", "semver", "purl", "version"]
categories = [
    "development-tools",
    "development-tools::build-utils",
    "command-line-utilities",
    "value-formatting",
]

[dependencies]
# alpm-version = { path = "../alpm-version" }
# apk-version = { path = "../apk-version" }
# cran-version = { path = "../cran-version" }
# debian-version = { path = "../debian-version" }
# luarocks-version = { path = "../luarocks-version" }
# maven-version = { path = "../maven-version" }
# opam-version = { path = "../opam-version" }
# rpm-version = { path = "../rpm-version", package = "rpm-vercmp" }
# semantic-version = { path = "../semantic-version" }
alpm-version = { version = "0.1.0" }
apk-version = { version = "0.1.0" }
cran-version = { version = "0.1.0" }
debian-version = { version = "0.1.0" }
luarocks-version = { version = "0.1.0" }
maven-version = { version = "0.1.0" }
opam-version = { version = "0.1.0" }
rpm-version = { version = "0.1.0", package = "rpm-vercmp" }
semantic-version = { version = "0.1.0" }

version-compare = "0.2.1"

[build-dependencies]
# ws-build = { path = "../ws-build" }
ws-build = { version = "0.1.0" }
cbindgen = { version = "0.29.2", optional = true }

# [lib]
# name = "vercmp"
# crate-type = [
#     "cdylib",
#     # "rlib",
#     # "staticlib"
# ]

[features]
default = []
# Generate Rust FFI bindings for invoking C libraries
generate-bindings = ["ws-build/generate-bindings"]
# Generate C FFI interface for calling Rust from C
generate-capi = ["cbindgen"]
