/* automatically generated by rust-bindgen 0.72.1 */

pub const RPM_VERSION_EQUAL: u32 = 1;
pub const RPM_VERSION_LESS: u32 = 0;
pub const RPM_VERSION_GREATER: u32 = 2;
unsafe extern "C" {
    pub fn rpm_version_compare(
        a: *const ::std::os::raw::c_char,
        b: *const ::std::os::raw::c_char,
    ) -> i32;
}
