/* automatically generated by rust-bindgen 0.72.1 */

pub const APK_VERSION_EQUAL: u32 = 0;
pub const APK_VERSION_LESS: u32 = 1;
pub const APK_VERSION_GREATER: u32 = 2;
unsafe extern "C" {
    #[doc = " 比较两个 APK 版本字符串\n @return APK_VERSION_EQUAL, APK_VERSION_LESS, APK_VERSION_GREATER,\n         或 (APK_VERSION_LESS | APK_VERSION_GREATER) 表示不可比较"]
    pub fn apk_version_compare(
        str1: *const ::std::os::raw::c_char,
        str2: *const ::std::os::raw::c_char,
    ) -> i32;
}
