/* automatically generated by rust-bindgen 0.72.1 */

pub const ALPM_VERSION_EQUAL: u32 = 1;
pub const ALPM_VERSION_LESS: u32 = 0;
pub const ALPM_VERSION_GREATER: u32 = 2;
unsafe extern "C" {
    pub fn alpm_version_compare(
        str1: *const ::std::os::raw::c_char,
        str2: *const ::std::os::raw::c_char,
    ) -> i32;
}
