[package]
name = "compare"
version = "0.1.0"
edition = "2024"

[dependencies]
apk-version = { path = "../apk-version" }
debian-version = { path = "../debian-version" }
semantic-version = { path = "../semantic-version" }
rpm-version = { path = "../rpm-version" }
alpm-version = { path = "../alpm-version" }
version-compare = "0.2.1"

[build-dependencies]
ws-build = { path = "../ws-build" }
cbindgen = { version = "0.29.2", optional = true }

# [lib]
# name = "vercmp"
# crate-type = [
#     "cdylib",
#     # "rlib",
#     # "staticlib"
# ]

[features]
default = []
# 生成 Rust 调用 C 的绑定
generate-bindings = ["ws-build/generate-bindings"]
# 生成 C 调用 Rust 的 FFI 接口
generate-capi = ["cbindgen"]
