[package]
name = "compare"
version = "0.1.0"
edition = "2024"

[dependencies]
apk-version = { path = "../apk-version" }
debian-version = { path = "../debian-version" }
semantic-version = { path = "../semantic-version" }
rpm-version = { path = "../rpm-version" }
alpm-version = { path = "../alpm-version" }
